<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration [
        <!ELEMENT generatorConfiguration (context)*>
        <!ELEMENT context (plugin|jdbcConnection|javaTypeResolver|javaModelGenerator|sqlMapGenerator|javaClientGenerator|table)*>
        <!ATTLIST context
                id CDATA #REQUIRED
                targetRuntime CDATA #REQUIRED>
        <!ELEMENT plugin (#PCDATA)>
        <!ATTLIST plugin
                type CDATA #REQUIRED>
        <!ELEMENT jdbcConnection (#PCDATA)>
        <!ATTLIST jdbcConnection
                driverClass CDATA #REQUIRED
                connectionURL CDATA #REQUIRED
                userId CDATA #REQUIRED
                password CDATA #REQUIRED>
        <!ELEMENT javaTypeResolver (property)*>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT javaModelGenerator (property)*>
        <!ATTLIST javaModelGenerator
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT sqlMapGenerator (property)*>
        <!ATTLIST sqlMapGenerator
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT javaClientGenerator (property)*>
        <!ATTLIST javaClientGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT table (#PCDATA)>
        <!ATTLIST table
                domainObjectName CDATA #REQUIRED
                tableName CDATA #REQUIRED>
        ]>
<generatorConfiguration>

    <context id="DB2Tables" targetRuntime="MyBatis3">

        <plugin type="org.mybatis.generator.plugins.RowBoundsPlugin"></plugin>
        <jdbcConnection driverClass="org.h2.Driver"
                        connectionURL="jdbc:h2:E:/db/community"
                        userId="root"
                        password="123">
        </jdbcConnection>

        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
        </javaTypeResolver>

        <javaModelGenerator targetPackage="com.xqy.cool.cool.model" targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>

        <sqlMapGenerator targetPackage="mapper" targetProject="src/main/resources">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>

        <javaClientGenerator type="XMLMAPPER" targetPackage="com.xqy.cool.cool.mapper"
                             targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>

        <table tableName="user" domainObjectName="User"></table>
        <table tableName="question" domainObjectName="Question"></table>
    </context>
</generatorConfiguration>